apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    chart: {{.Chart.Name}}
spec:
  selector:
    matchLabels:
      app: {{.Values.name}}
  replicas: {{ default 1 .Values.deployment.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.deployment.image}}
        imagePullPolicy: Allways
        ports:
        - containerPort: {{.Values.deployment.containerPort | int }}