apiVersion: apps/v1
kind: Deployment
metadata: {{ .Chart.Name}}
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ default 1 .Values.deployment.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.deployment.image }}"
        imagePullPolicy: Allways
        ports:
        - containerPort: {{ .Values.deployment.containerPort | int }}